### ISSUE TITLE
websocket issue: Something went wrong in real-time service

### ISSUE THREAD

**Issue by zeta-omega-chi** [ayaka-notes/overleaf#6]
作者的镜像在本地（`wsl2, openSUSE-Tumbleweed`）上跑的非常完美，编译[400+页的书](https://github.com/wenweili/AlJabr-1)只要一分多钟，但是当我尝试把它搬上阿里云ECS（2核4G）时，`launchpad`的诊断界面显示`Something went wrong in real-time service`：

![image](https://github.com/ayaka-notes/overleaf/assets/130829104/4d6601f5-04da-4a47-a9e9-d8ea5a1d2a0e)

尝试进入编辑界面，一直在加载：

![image](https://github.com/ayaka-notes/overleaf/assets/130829104/a9a2393d-5471-4001-a851-786b4d13ea37)

## 容器信息
容器运行的时候用`docker exec -it sharelatex /bin/bash`进入`sharelatex`容器，里面的`/var/log/overleaf/real-time.log`信息如下：

```json
{
  "name": "real-time",
  "hostname": "57162a1da944",
  "pid": 182,
  "level": 30,
  "userId": "65efbe4f5c02b2d3ea0c2ee4",
  "projectId": "404404404404404404404404",
  "clientId": "T73i2CxNjRzyxek6W-BB",
  "remoteIp": "::1",
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36",
  "msg": "user joining project",
  "time": "2024-04-04T06:43:06.431Z",
  "v": 0
}
{
  "name": "real-time",
  "hostname": "57162a1da944",
  "pid": 182,
  "level": 50,
  "project_id": "404404404404404404404404",
  "user_id": "65efbe4f5c02b2d3ea0c2ee4",
  "client_id": "T73i2CxNjRzyxek6W-BB",
  "err": {
    "message": "connect ECONNREFUSED ::1:3000",
    "name": "Error",
    "stack": "Error: connect ECONNREFUSED ::1:3000\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)\nTaggedError: join project request failed\n    at Request._callback (/overleaf/services/real-time/app/js/WebApiManager.js:33:18)\n    at self.callback (/overleaf/node_modules/request/request.js:185:22)\n    at Request.emit (node:events:517:28)\n    at Request.onRequestError (/overleaf/node_modules/request/request.js:877:8)\n    at ClientRequest.emit (node:events:517:28)\n    at Socket.socketErrorListener (node:_http_client:501:9)\n    at Socket.emit (node:events:517:28)\n    at emitErrorNT (node:internal/streams/destroy:151:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)",
    "info": {},
    "code": "ECONNREFUSED"
  },
  "method": "joinProject",
  "msg": "server side error in joinProject",
  "time": "2024-04-04T06:43:06.433Z",
  "v": 0
}
```

推测是mongodb启动了但没连上，因为`docker ps`显示的三个容器（`sharelatex`, `mongo`, `redis`）都是正常up的

## 系统信息
这是系统的基本信息：
```
➜  ~ lsb_release -a
LSB Version:    core-11.1.0ubuntu4-noarch:security-11.1.0ubuntu4-noarch
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy
```
用的是`test-local/`，`docker-compose.yml`  `docker-compose.image.yml` `init.sh` `up.sh`啥也没动，直接`scp`到服务器上去的，后面我甚至尝试了除`texlive-full`以外全`docker save`一份再在服务器上`docker load`，然而依旧是something went wrong，本地的倒是一点问题没有

![image](https://github.com/ayaka-notes/overleaf/assets/130829104/1ac89081-fc8a-4a84-90f2-7fa4d9235da4)

---

P.S. 按照[这个流程](https://github.com/overleaf/toolkit/blob/master/doc/quick-start-guide.md)跑overleaf ce没有问题，但把`sharelatex`镜像换成别人的镜像（https://github.com/tuetenk0pp/sharelatex-full) 又有点问题：
```
sharelatex  | Cannot connect to mongodb
sharelatex  | MongooseServerSelectionError: connect ECONNREFUSED 192.168.48.1:27017
sharelatex  |     at Connection.openUri (/overleaf/services/web/node_modules/mongoose/lib/connection.js:825:32)
sharelatex  |     at /overleaf/services/web/node_modules/mongoose/lib/index.js:414:10
sharelatex  |     at /overleaf/services/web/node_modules/mongoose/lib/helpers/promiseOrCallback.js:41:5
sharelatex  |     at new Promise (<anonymous>)
sharelatex  |     at promiseOrCallback (/overleaf/services/web/node_modules/mongoose/lib/helpers/promiseOrCallback.js:40:10)
sharelatex  |     at Mongoose._promiseOrCallback (/overleaf/services/web/node_modules/mongoose/lib/index.js:1288:10)
sharelatex  |     at Mongoose.connect (/overleaf/services/web/node_modules/mongoose/lib/index.js:413:20)
sharelatex  |     at Object.<anonymous> (/overleaf/services/web/app/src/infrastructure/Mongoose.js:19:36)
sharelatex  |     at Module._compile (node:internal/modules/cjs/loader:1356:14)
sharelatex  |     at Module._extensions..js (node:internal/modules/cjs/loader:1414:10) {
sharelatex  |   reason: TopologyDescription {
sharelatex  |     type: 'Unknown',
sharelatex  |     servers: Map(1) { 'dockerhost:27017' => [ServerDescription] },
sharelatex  |     stale: false,
sharelatex  |     compatible: true,
sharelatex  |     heartbeatFrequencyMS: 10000,
sharelatex  |     localThresholdMS: 15,
sharelatex  |     setName: null,
sharelatex  |     maxElectionId: null,
sharelatex  |     maxSetVersion: null,
sharelatex  |     commonWireVersion: 0,
sharelatex  |     logicalSessionTimeoutMinutes: null
sharelatex  |   },
sharelatex  |   code: undefined
sharelatex  | }
sharelatex  | *** /etc/my_init.d/98_check_db_access.sh failed with status 1
sharelatex  |
sharelatex  | *** Killing all processes...
sharelatex  | Apr  4 08:33:16 443ccdb7e6ff syslog-ng[89]: syslog-ng shutting down; version='3.25.1'
sharelatex exited with code 0
```

**Comment by Musicminion** [comment]
你用的是nginx做端口转发吗，就是说你是用域名部署的`https://your.domain.com`，还是用的裸的ip访问的？

websocket首先建议用裸ip+端口访问测试一下，如果没有问题再换IP。否则可能是nginx配置的时候没有配好。

mongodb启动了但没连上，那么你用户甚至是没有办法登录的哦，所以不可能

**Comment by Musicminion** [comment]
稍等一下，我可能需要测试一下，然后目前来看维护四个版本这种启动方法太过繁琐，正在考虑合并一下或者迁移

**Comment by Musicminion** [comment]
我准备了一台全新的ecs，阿里云的2c 4g，ubuntu 22.04 EFI加固版的测试：

我是这么装docker的，然后脚本里面的docker-compose要改成docker compose()，就是把脚本里面的横线替换到
```
# install docker
for pkg in docker.io docker-doc docker-compose docker-compose-v2 podman-docker containerd runc; do sudo apt-get remove $pkg; done

# Add Docker's official GPG key:
sudo apt-get update
sudo apt-get install -y ca-certificates curl
sudo install -m 0755 -d /etc/apt/keyrings
sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
sudo chmod a+r /etc/apt/keyrings/docker.asc

# Add the repository to Apt sources:
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
  $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
  sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
sudo apt-get update

sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

```
然后我用的test-codespace，没有问题，

![image](https://github.com/ayaka-notes/overleaf/assets/84625273/64caf55f-dc33-4455-8d46-7597c0cc5ed6)


![image](https://github.com/ayaka-notes/overleaf/assets/84625273/60644a11-de41-4e42-b5bf-6430053067db)



----
相反补一下我今天wsl用来测试，还出现了很多问题，今天我测的时候发现docker不能编译了，直接挂了，严重怀疑docker出现了问题，或者是wsl（问题就是不能编译，挂载了目录之后没有文件，一想到前不久我更新了我电脑里面的docker，我就觉得可能是这个问题

**Comment by Musicminion** [comment]
补一下wsl docker不能编译的问题，是因为docker的4.28 desktop有问题，属于是docker的问题，我猜测你这可能也是和docker版本有关，对于linux的建议更新到docker的最新版，对于windows desktop版，4.27测试后没有问题

耗费了我一下午时间，最后发现是docker的锅，[○･｀Д´･ ○]

**Comment by zeta-omega-chi** [comment]
我用的是裸ip+端口访问，
![Screenshot_20240410_074722_mark via](https://github.com/ayaka-notes/overleaf/assets/130829104/d1295a51-9081-45e5-8cea-656369977b9a)
啥也没动，更新了overleaf镜像，换成 test-codespace 然后就好了🤦

**Comment by zeta-omega-chi** [comment]
还有一个小问题，在wsl中也存在
![Screenshot_20240410_075747_mark via](https://github.com/ayaka-notes/overleaf/assets/130829104/4d9baf83-d05c-440d-804a-e48bdc931425)
用创建样例项目创建一个project，打开之后就是上面这个样子：`此编译未生成 PDF`，清除缓存、换编译器都无效，然后`output.stderr`如下
![Screenshot_20240410_075723_com android htmlviewer](https://github.com/ayaka-notes/overleaf/assets/130829104/b6cfd306-8c1d-4b61-82a1-f2576e2edd30)
`output.stdout`:
![Screenshot_20240410_080631_com android htmlviewer](https://github.com/ayaka-notes/overleaf/assets/130829104/b635aef3-5d45-4ead-a5f4-0c9618f47303)

**Comment by Musicminion** [comment]
可能是overleaf更新修复了bug吧，我每天还在合并代码的
